objects/Account_Team__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Owner</fullName>
                </value>
                <value>
                    <fullName>Business Development</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Construction Lead</fullName>
                </value>
                <value>
                    <fullName>Contracts Team</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Development Lead</fullName>
                </value>
                <value>
                    <fullName>Engineering - Civil</fullName>
                </value>
                <value>
                    <fullName>Engineering - Electrical</fullName>
                </value>
                <value>
                    <fullName>Engineering - Mechanical</fullName>
                </value>
                <value>
                    <fullName>Engineering - SCADA</fullName>
                </value>
                <value>
                    <fullName>Engineering - Structural</fullName>
                </value>
                <value>
                    <fullName>Engineering - Survey</fullName>
                </value>
                <value>
                    <fullName>Estimator</fullName>
                </value>
                <value>
                    <fullName>Executive Champion</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>HSQE</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Operation Maintenance</fullName>
                </value>
                <value>
                    <fullName>Opportunity Owner</fullName>
                </value>
                <value>
                    <fullName>Permitting - Property Manager</fullName>
                </value>
                <value>
                    <fullName>PM - Construction</fullName>
                </value>
                <value>
                    <fullName>PM - Development</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Proposal Manager</fullName>
                </value>
                <value>
                    <fullName>Technical Team</fullName>
                </value>
                <value>
                    <fullName>Transmission Team</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Account_Team</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Team Member</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Account Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Activity_Status__c</fullName>
        <formula>IF(ISNULL(Last_Client_Meeting__c),&quot;No Client Meeting Has Ever Been Created&quot;,
IF(ISNULL(Expected_Activity_Date__c),&quot;No Contact Frequency Set&quot;,
IF(Expected_Activity_Date__c &lt; Today(),&quot;LATE&quot;,
IF(Expected_Activity_Date__c - Today() &lt; 8, &quot;Activity Due This Week&quot;,
&quot;On Schedule&quot;
))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Meeting Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Frequency__c</fullName>
        <label>Contact Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Bi-Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Biannually</fullName>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Influence__c</fullName>
        <description>To mark the level of influence of a contact at a key account.</description>
        <inlineHelpText>What is the level of influence this individual has?

Values 1 to 10. (10 being high)

When two contacts have the same level then mark one with an extra point 5 (0.5) value to allow them both  to be seen on the Sponsor Blocker chart.</inlineHelpText>
        <label>Influence</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Key_Decision_Maker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Decision Maker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Client_Meeting__c</fullName>
        <inlineHelpText>Date stamp of when the last Face to Face Meeting was held for this Contact.</inlineHelpText>
        <label>Last Client Meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If left blank, this field will automatically pull the USER from within the Contact&apos;s &quot;Owner&quot; field and replace it with the associated RES CONTACT.</inlineHelpText>
        <label>Primary Contact Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>This Contact does not exist on one of the &quot;Renewable Energy System&quot; Accounts. Please create their Contact here: https://res-group.lightning.force.com/one/one.app#/sObject/001i000000svaF8AAI/view</errorMessage>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>contains</operation>
                <value>Renewable Energy Systems</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>contains</operation>
                <value>RES T&amp;D</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Primary Contact Owner)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>RES Employee who is also responsible for the relationship of this Contact and the necessary outreach.</inlineHelpText>
        <label>Secondary Contact Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>This RES Employee must already exist as a Contact on one of the &quot;Renewable Energy Systems&quot; Accounts. If they don&apos;t exist yet, please add them to as new Contact on the parent, or one of the subsidiary RES Accounts.</errorMessage>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>contains</operation>
                <value>Renewable Energy Systems</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>contains</operation>
                <value>RES T&amp;D</value>
            </filterItems>
            <infoMessage>Must be a Contact on one of the &quot;Renewable Energy System&quot; Accounts.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <inlineHelpText>Contact&apos;s relationship to RES. NOT their Title.</inlineHelpText>
        <label>Role</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_of_RES__c</fullName>
        <inlineHelpText>What is the Client&apos;s perception of RES?  Please input a range between -5 and +5.

Definitions of these values can be found via the URL link on this contact page (below).</inlineHelpText>
        <label>View of RES</label>
        <precision>2</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/KA_Strategic_Objective__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>KA_Strategic_Objectives</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Strategic Objective</label>
    <nameField>
        <label>Strategic Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>COD_Date__c</fullName>
        <label>COD</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <description>Vertiba3/10/2014 - Phase1</description>
        <inlineHelpText>Enter a MW figure indicating the Size/Capacity of this project.</inlineHelpText>
        <label>Size (MWac)</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MB</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KAMController.cls
public with sharing class KAMController {
  	
 	private Account acc;
    private List <Contact> kdmContacts;
    private List <Account_Team__c> accMembers;
    private List <Opportunity> openOpps;
    private List <Opportunity> closedOpps;
    private List <Opportunity> closedBrokerOpps;
    private List <Opportunity> openBrokerOpps;
    private List <KA_Strategic_Objective__c> kasos;
    private List <KA_Strategic_Objective__c> archivedKasos;
    
    public KAMController(ApexPages.StandardController controller) {
        this.acc = (Account)controller.getRecord();
        //String accName = acc.Name;
        //String fileName = 'KAM:' + accName + '.pdf'; Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=' + fileName);
    }

    public List <Contact> getKDMContacts() {
        kdmContacts = [Select id, AccountId, Name, Title, Key_Decision_Maker__c, ReportsTo.Name, Owner.Name, Relationship_Owner__c,Primary_Contact_Owner__c,
        				Contact_Activity_Status__c, Contact_Frequency__c, Last_Client_Meeting__c, LastActivityDate,View_of_RES__c,Influence__c
        from Contact where AccountId = :acc.id AND Key_Decision_Maker__c=True 
        ORDER BY Influence__c DESC, Name DESC Nulls Last];
        return kdmContacts;
    }
    
    public List <Account_Team__c> getAccMembers () {
        accMembers = [Select id, Account__c, Team_Member__c,Role__c
        from Account_Team__c where Account__c = :acc.id 
        ORDER BY Role__c DESC];
        return accMembers;
    }
    
    public List <Opportunity> getOpenOpps() {
        openOpps = [Select id, AccountId, Name, StageName, CloseDate, Size__c, OwnerId,COD_Date__c,State_Province__c,
        				Priority__c, Contract_Type__c, Business_Line__c
        from Opportunity where AccountId = :acc.id AND IsClosed=False AND StageName<>'Tabled' AND (Priority__c = 'Priority 1' OR Priority__c = 'Priority 2')
        ORDER BY CloseDate ASC];
        return openOpps;
    }
    
    public List <Opportunity> getClosedOpps() {
        closedOpps = [Select id, AccountId, Name, StageName, CloseDate, Size__c, OwnerId,COD_Date__c,State_Province__c,
        				Closed_Reason_Notes__c, Outcome_Reason__c, Contract_Type__c, Business_Line__c,Broker_Account__r.Name,Broker_Account__c
        from Opportunity where (AccountId = :acc.id OR Broker_Account__r.Id = :acc.id) AND IsClosed=True AND CloseDate >= LAST_N_FISCAL_QUARTERS:2
        Order BY CloseDate ASC];
        return closedOpps;
    }
    
    public List <Opportunity> getBrokerOpps() {
        openBrokerOpps = [Select id, AccountId, Name, StageName, CloseDate, Size__c, OwnerId,COD_Date__c,State_Province__c,
        				Priority__c, Contract_Type__c, Business_Line__c,Broker_Account__r.Name,Broker_Account__c
        from Opportunity where Broker_Account__r.Id = :acc.id AND IsClosed=False AND StageName<>'Tabled' AND (Priority__c = 'Priority 1' OR Priority__c = 'Priority 2')
        ORDER BY CloseDate ASC];
        return openBrokerOpps;
    }
    
     public List <Opportunity> getClosedBrokerOpps() {
        closedBrokerOpps = [Select id, AccountId, Name, StageName, CloseDate, Size__c, OwnerId,COD_Date__c,State_Province__c,
        				Priority__c, Contract_Type__c, Business_Line__c,Broker_Account__r.Name,Broker_Account__c
        from Opportunity where Broker_Account__r.Id = :acc.id AND IsClosed=True AND CloseDate >= LAST_N_FISCAL_YEARS:1
        Order BY CloseDate ASC];
        return closedBrokerOpps;
    }
    
    public List <KA_Strategic_Objective__c> getKASOs() {
        kasos = [Select id, Account__c, Name, Objective_Owner__c, Category__c, Completed__c, Date_for_Closure__c, Objective_Title__c, Objective_Description__c,	Update__c
        from KA_Strategic_Objective__c where Account__c = :acc.id AND ( Completed__c = false OR Date_for_Closure__c >= TODAY )
        ORDER BY Date_for_Closure__c ASC];
        return kasos;
    }
    
    public List <KA_Strategic_Objective__c> getArchivedKASOs() {
        archivedKasos = [Select id, Account__c, Name, Objective_Owner__c, Category__c, Completed__c, Date_for_Closure__c, Objective_Title__c, Objective_Description__c,	Update__c
        		 FROM KA_Strategic_Objective__c 
                 WHERE Account__c = :acc.id 
                 AND (Completed__c = true OR (Date_for_Closure__c < TODAY AND Date_for_Closure__c >= LAST_N_MONTHS:24))                
                 ORDER BY Date_for_Closure__c ASC];
        return archivedKasos;
    }
    
}