objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Key_Decision_Maker__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Key Decision Maker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Relationship_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>RES Employee who is also responsible for the relationship of this Contact and the necessary outreach.</inlineHelpText>
        <label>Secondary Contact Owner</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>This RES Employee must already exist as a Contact on one of the &quot;Renewable Energy Systems&quot; Accounts. If they don&apos;t exist yet, please add them to as new Contact on the parent, or one of the subsidiary RES Accounts.</errorMessage>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>contains</operation>
                <value>Renewable Energy Systems</value>
            </filterItems>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>contains</operation>
                <value>RES T&amp;D</value>
            </filterItems>
            <infoMessage>Must be a Contact on one of the &quot;Renewable Energy System&quot; Accounts.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GoogleControllerHierarchy.cls
global with sharing class GoogleControllerHierarchy {
	
	public GoogleControllerHierarchy(ApexPages.StandardController controller){
		this.acc =[Select Id, Name From Account Where Id= :controller.getId()];
	}
	public Account acc { get; set; }
	public String accountId { get; set; }
	public GoogleControllerHierarchy() {
    }
     
    @RemoteAction   
    global static List<Contact>loadContacts(Id accountId) {
        return [Select Id, Name, Email, Title, Key_Decision_Maker__c, OwnerId, Department, ReportsToId, Relationship_Owner__c 
        from Contact Where AccountId = :accountId order by Name DESC];
    }   
}