objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Asset Purchase</fullName>
                </value>
                <value>
                    <fullName>Asset Sale</fullName>
                </value>
                <value>
                    <fullName>Auction</fullName>
                </value>
                <value>
                    <fullName>BOP/BOS</fullName>
                </value>
                <value>
                    <fullName>BOT</fullName>
                </value>
                <value>
                    <fullName>Construction Only</fullName>
                </value>
                <value>
                    <fullName>DPA</fullName>
                </value>
                <value>
                    <fullName>EPC</fullName>
                </value>
                <value>
                    <fullName>EPCM</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Partner / JV</fullName>
                </value>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>SPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RES_Technology_Type__c</fullName>
        <description>Vertiba 2/1/2014 - Created to track the technology information ssociated to the opportunity</description>
        <label>Technology Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Wind - Onshore</fullName>
                </value>
                <value>
                    <fullName>Wind - Offshore</fullName>
                </value>
                <value>
                    <fullName>Solar</fullName>
                </value>
                <value>
                    <fullName>Storage</fullName>
                </value>
                <value>
                    <fullName>Hydro</fullName>
                </value>
                <value>
                    <fullName>Transmission</fullName>
                </value>
                <value>
                    <fullName>Distribution</fullName>
                </value>
                <value>
                    <fullName>Collection Systems</fullName>
                </value>
                <value>
                    <fullName>Substation</fullName>
                </value>
                <value>
                    <fullName>Tower Wiring</fullName>
                </value>
                <value>
                    <fullName>Hydrogen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContentDocumentLinkTriggerTest.cls
@isTest
private class ContentDocumentLinkTriggerTest
{
    @isTest
    static void itShould()
    {
        Account acc = new Account(recordtypeId='012i0000001AwFvAAK',name='test acc',Website='www.test.com');
        insert acc;
        //Contact con = new Contact(lastname='test cont',accountid=acc.id);
        //insert con;
        Opportunity opp = new Opportunity(recordtypeId='012i0000001B24kAAC',name='testoppty',AccountId=acc.id,stageName='Prospecting', Contract_Type__c='EPC', RES_Technology_Type__c='Onshore - Wind', closedate=system.today());
        insert opp;

        ContentVersion content=new ContentVersion(); 
            content.Title='Header_Picture1'; 
            content.PathOnClient='/' + content.Title + '.jpg'; 
            Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
            content.VersionData=bodyBlob; 
            //content.LinkedEntityId=sub.id;
            content.origin = 'H';
        insert content;
        ContentDocumentLink contentlink=new ContentDocumentLink();
            contentlink.LinkedEntityId=opp.id;
            contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
            contentlink.ShareType = 'V';
            test.starttest();
        insert contentlink;
test.stoptest();

    }
}